name: GitHub Action CI/CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t docker_test:latest .
          echo "🐧 Congratulations! Docker image built successfully."
      
      - name: Run tests inside container
        run: |
          docker run docker_test:latest sh -c "pip install --no-cache-dir pytest && python -m pytest tests/"
          echo "✅ All tests passed successfully."
      
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "🔒 Successfully logged in to GitHub Container Registry."

      - name: Push image
        env:
          REPO_LC: ${{ github.repository }}
        run: |
          REPO_LC=$(echo "$REPO_LC" | tr '[:upper:]' '[:lower:]')
          docker tag docker_test:latest ghcr.io/$REPO_LC:latest
          docker push ghcr.io/$REPO_LC:latest
          echo "🚀 Docker image pushed to GitHub Container Registry successfully."

